In [7]:
import numpy as np

# 3D Matrix
matrix = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

# 2D Vector
vector = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

result = matrix + vector

print(result)

[[[11 22 33]
  [44 55 66]]

 [[17 28 39]
  [50 61 72]]]


In [ ]:
#JOINING ARRAYS IN NUMPY 
import numpy as np
a = np.array([1, 2 , 3])
b = np.array([4, 5 , 6])
print("Concatenate:", np.concatenate([a, b]))
print("Stack:", np.stack([a, b]))
x = np.array([[1, 2],
             [3, 4]])
y = np.array([[5, 6],
              [7, 8]])
print("\nVertical stack:")
print(np.vstack([x, y]))
print("\nHorizontal stack:")
print(np.hstack([x, y]))


Concatenate: [1 2 3 4 5 6]
Stack: [[1 2 3]
 [4 5 6]]

Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]


In [4]:
#splitting methods
arr = np.arange(1, 11)
print("split:")
print(np.split(arr, 2))
print("\nArray split into 3 parts:")
print(np.array_split(arr, 3))

split:
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

Array split into 3 parts:
[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [5]:
#random 
rng = np.random.default_rng(42)
print("Random numbers:")
print(rng.integers(1, 10, size=5))
print("\nRandom floats:")
print(rng.random(5))
print("\nNormal distributions:")
print(rng.normal(loc=0, scale=1, size=5))

Random numbers:
[1 7 6 4 4]

Random floats:
[0.69736803 0.09417735 0.97562235 0.7611397  0.78606431]

Normal distributions:
[-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307 ]


In [6]:
x = rng.random((4, 3))
print(x)
print("Shape:", x.shape)

[[0.82276161 0.4434142  0.22723872]
 [0.55458479 0.06381726 0.82763117]
 [0.6316644  0.75808774 0.35452597]
 [0.97069802 0.89312112 0.7783835 ]]
Shape: (4, 3)


In [7]:
x = rng.random((2, 2, 3))
print(x)
print("Shape:", x.shape)

[[[0.19463871 0.466721   0.04380377]
  [0.15428949 0.68304895 0.74476216]]

 [[0.96750973 0.32582536 0.37045971]
  [0.46955581 0.18947136 0.12992151]]]
Shape: (2, 2, 3)


In [9]:
#sampling
students = np.array(["A", "B",  "C", "D", "E"])
print("One student:", rng.choice(students))
print("Three students:", rng.choice(students, size=3, replace=False))
print("Three students:", rng.choice(students, size=3, replace=True))

One student: D
Three students: ['C' 'B' 'A']
Three students: ['D' 'A' 'B']


In [14]:
#set operations
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("Intersection:", np.intersect1d(a, b))
print("union:", np.union1d(a, b))
print("A - B:", np.setdiff1d(a,b))
np.all(np.isin(a, b))

Intersection: [3 4]
union: [1 2 3 4 5 6]
A - B: [1 2]


np.False_

In [17]:
#matrix operations
A = np.array([[1, 2],
            [3, 4]])
B = np.array([[5, 6],
            [7, 8]])
print("Element-wise multiplication:")
print(A * B)
print("\nMatrix multiplication:")
print(A @ B)
print("\nDot product:")
print(np.dot(A, B))

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Dot product:
[[19 22]
 [43 50]]


In [ ]:
A = np.array([[1, 2],
              [3, 4]], dtype=float)
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))
print("\nA @ inverse:")
print( A @ np.linalg.inv(A))

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ inverse:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
